server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitMq的服务信息
        defaultRabbit:  #表示定义的名称，用于binding整合
          type: rabbit  #消息组件类型
          environment:  #设置RabbitMQ的相关的环境配置
            spring:
              #RabbitMQ相关配置,15672是web管理端口
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称，表示是消费者
          destination: studyExchange  #表示要是用的Exchange名称定义，队列名称
          content-type: application/json #设置消息类型，本次为json，文本则用"text/plain"
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: lizhiqiangA

eureka:
  client:
    service-url:
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: cloud-stream-consumer8803
    prefer-ip-address: true #访问路径显示IP地址，方便排查
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔(默认是30秒)
    lease-expiration-duration-in-seconds: 5 #服务在5秒内没法送心跳连接，被注册中心移除
