server:
  port: 8001

spring:
  application:
    name: nacos-sentinel-order-consumer
  cloud:
    nacos:
      discovery:
        #nacos 服务注册中心地址
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #配置 sentinel dashboard 地址
        dashboard: 127.0.0.1:8080
        #默认8719端口，假如被占用会自动依次从8719+1扫描，直至找到未被占用的端口
        port: 8719



#自定义配置，消费者访问微服务名称
service-url:
  nacos-user-service: http://nacos-sentinel-payment-provider