server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #nacos 服务注册中心地址
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #配置 sentinel dashboard 地址
        dashboard: 127.0.0.1:8080
        #默认8719端口，假如被占用会自动依次从8719+1扫描，直至找到未被占用的端口
        port: 8719
      #添加sentinel数据源,将限流配置规则持久化进Nacos保存
      datasource:
        ds1:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow


#暴露监控端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'  #统一写法