server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #Gateway配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh1           #路由ID，没有固定规则，但要求唯一，建议配合服务名命名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址 （静态路由，没什么用）
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址 （动态路由）
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由

        - id: payment_routh2           #路由ID，没有固定规则，但要求唯一，建议配合服务名命名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**    #断言，路径相匹配的进行路由
            - After=2020-09-15T15:07:39.177+08:00[Asia/Shanghai]
            #- Cookie=username,lzq
            #- Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性并且值为整数的正则表达式
            - Method=GET
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加一对请求头，名称为X-Request-Id值为1024




eureka:
  client:
    #表示是否将自己注册进Eureka Server,默认为true
    register-with-eureka: true
    #是否从Eureka Server抓取已有的注册信息，默认为true，单节点无所谓，集群模式必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

  instance:
    instance-id: cloud-gateway9527
    prefer-ip-address: true #访问路径显示IP地址，方便排查
    hostname: cloud-gateway-service