server:
  port: 2001

spring:
  application:
    name: nacos-seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        #自定义事务组名称,需要与seata-server中对应
        tx-service-group: lzq_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: 123456


#开启feign熔断降级
feign:
  hystrix:
    enabled: true

#设置feign客户端超时时间，openFeign默认支持 ribbon
ribbon:
  #指的是建立连接所用时间，适用于网络状况正常情况下，两端连接所用时间
  ReadTimeout: 5000
  #指建立连接后从服务器读取到可用资源所用时间
  ConnectTimeout: 5000

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #所有Entity别名类所在包
  type-aliases-package: com.lizhiqiang.springcloud.entities

#自定义配置，openFeign微服务调用好使用
service-url:
  nacos-seata-storage-service: http://nacos-seata-storage-service
  nacos-seata-account-service: http://nacos-seata-account-service
