server:
  port: 8000

spring:
  application:
    name: cloud-consumer-consul
####consul注册中心配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}



