server:
  port: 8003

spring:
  application:
    name: cloud-payment-consul-service
####consul注册中心配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}



